### ISSUE TITLE
cannot set voltage remotely via serial port

### ISSUE THREAD

**Issue by coffinshaker** [kanflo/opendps#112]
When I remotely run the command to set voltage it returns "ok" but nothing changes. Shouldn't there be a line like this:

`cv_voltage.value = ivalue;`

just before calling the following function in line 162 in file `func_cv.c`:

`voltage_changed(&cv_voltage);`

or is there a reason the voltage cannot be changed this way?

**Comment by kanflo** [comment]
Hmm, I will try to reproduce (and fix ;) that this weekend. Thanks for reporting!

**Comment by Xenoamor** [comment]
Well spotted @coffinshaker!

**Comment by kanflo** [comment]
Reminds me that I need to build an automated test environment in my basement :)
