### ISSUE TITLE
DPS5015 Current Value only 9.999

### ISSUE THREAD

**Issue by sq9fk** [kanflo/opendps#138]
Hello,
I noticed little bug:
When try to adjust Current to 15.000 A, opendps shows 9.999 then 0.000 ending at 5.000 -> which was 15A according to real measure from external meter.

Can we make a bugfix for this?
IMO 10mA scale would be enough for this supply.

Piotr

**Comment by kanflo** [comment]
Hmmm, I recall that one being fixed some time ago. Seems to be an eager little bug ;)

**Comment by kanflo** [comment]
Fixed in #189
