### ISSUE TITLE
curent limit no presant , will be added ? 

### ISSUE THREAD

**Issue by finos2** [kanflo/opendps#14]
open dps is undergrade without the current limiter for usage in a lab , also ad in the front panel watts mesurment

**Comment by cleverfox** [comment]
Look at cc branch. And also you can read this pr https://github.com/kanflo/opendps/pull/12

**Comment by kanflo** [comment]
I currently have no plans to add the watt measurement to the front panel but pull requests are always welcome ;) The cc branch will/should be merged to master at some point.

**Comment by cleverfox** [comment]
@kanflo what do you think about reducing the font size? If we can reduce it to add one more line of text (probably small font), we can make opendps more flexible. 
I have few ideas about third display line: wattmeter, energy meter (useful for battery charging), and also in wattmeter mode probably useful feature is power limit (for example when checking LEDs when nominal current and/or voltage is unknown)

**Comment by kanflo** [comment]
Reducing the font size is doable, I created [font-convert.py](https://github.com/kanflo/opendps/blob/master/opendps/font-convert.py) just for that purpose. I guess at some point the UI will be configurable via JSON.

**Comment by roger-** [comment]
Can a voltage limit be set in CC mode?

**Comment by cleverfox** [comment]
In СС branch you can set maximum voltage and maximum current.

**Comment by roger-** [comment]
Will the CC branch be merged soon?

**Comment by kanflo** [comment]
I am hoping so, yes.
