### ISSUE TITLE
Flashing with other options/substitute for STLink

### ISSUE THREAD

**Issue by vogelfreiheit** [kanflo/opendps#16]
Is there anything that could be used for this purpose, replacing STLink? I have a GoodFET... but it seems I will have to wait it out until a ST-Link clone arrives from China.

**Comment by kanflo** [comment]
Anything thar can talk SWD with an STM32 will do such as a Black Magic Probe (BMP) or a J-Link (and of course an ST-Link). I have no experience with the GoodFET but it seems limited to MSP430s.
