### ISSUE TITLE
uint64_t is returned non-atomically without a guard lock

### ISSUE THREAD

**Issue by Xenoamor** [kanflo/opendps#173]
The tick function is not interrupt safe due to the use of a uint64_t. We should either implement guarding or reduce this to an atomic uint32_t

https://github.com/kanflo/opendps/blob/c1a8ab69d97ee3a329a2283ec88c49150537978c/opendps/tick.c#L30
https://github.com/kanflo/opendps/blob/c1a8ab69d97ee3a329a2283ec88c49150537978c/opendps/tick.c#L67

**Comment by kanflo** [comment]
Good catch. I would prefer guarding, anyone for uint32_t?
