### ISSUE TITLE
[question] Original modbus serial protocol?

### ISSUE THREAD

**Issue by Harvie** [kanflo/opendps#206]
Does the OpenDPS support original serial protocol provided by original firmware?
Can you please add this option to support the legacy protocol?

So when i have multiple devices and some of them have OpenDPS and some of them don't (because they're not supported, eg. #197) i can use all of them with the same protocol without having to sacrifice the possibility to flash OpenDPS?

**Comment by kanflo** [comment]
I could if someone raised a PR about it, I will most likely never get around to do it ;)

**Comment by shaneyake** [comment]
I would also like to see Modbus support, I have multiple units on one RS485 bus, would like to move over to OpenDPS but would need to change all my hardware and software layout.

Thanks
