### ISSUE TITLE
Confirmation: OpenDPS runs on DROK clones

### ISSUE THREAD

**Issue by Danukeru** [kanflo/opendps#212]
Verified on the 250W/5A DROK 180081 that can be found on Amazon.
untagged-fbd4280013628f4aefaf opendps_DPS5005.bin installed using st-linkv2
at offset 0x08001400
Followed by dpsboot.bin at 0x08000000.
Programming pinout is the same as the newer DPS models.

**Comment by kanflo** [comment]
A Chinese copy of a Chinese product it seems ;)
