### ISSUE TITLE
pycrc dependency incorrect

### ISSUE THREAD

**Issue by eovnu87435ds** [kanflo/opendps#215]
in dpsctl.py there is an error of a pycrc package is not installed. Unfortunately there seems to be a few different pycrc packages. The error states you need to install 'pycrc' via pip if you don't meet the requirement, however it seems that the proper package is 'pythoncrc'

**Comment by kanflo** [comment]
Thanks, I will fix that.

**Comment by Xenoamor** [comment]
Fixed in #213 ?

**Comment by kanflo** [comment]
Probably fixed in #220
