### ISSUE TITLE
PyCRC and PySerial not working or being found

### ISSUE THREAD

**Issue by haaxema** [kanflo/opendps#218]
Hi,

I have succesfully installed opendps on my DPS5005.
My problem is that dpsctl.py claims that pycrc and py serial are not installed.

I am using Ubuntu 20lts with Python 3.8

**Comment by polihedron** [comment]
https://github.com/kanflo/opendps#setup-dpsctlpy

**Comment by haaxema** [comment]
Thanks for the tip,

Turned out that I had the default PyCRC installed for an other script. Works fine now!

> https://github.com/kanflo/opendps#setup-dpsctlpy

**Comment by kanflo** [comment]
Fixed in #220
