### ISSUE TITLE
What serial connector type does RuiDeng DPS5005 uses?

### ISSUE THREAD

**Issue by Harvie** [kanflo/opendps#239]
Hello,
i am sorry for off topic question, but i don't know where else to ask...

Do you know what kind of connector does RuiDeng DPS5005 use? I think it might be **1.25mm Molex PicoBlade**, but when i measure that connector using calipers, it seems fraction of milimeter different. Can anyone please confirm if that is 1.25mm PicoBlade or something else? Thank you!

![image](https://user-images.githubusercontent.com/276504/119113348-4dfe4d80-ba25-11eb-9e79-43f3894fd46a.png)

**Comment by kanflo** [comment]
The last time I checked it was a JST GH (ie. 1.25mm)

**Comment by Harvie** [comment]
@kanflo Do you have same connectors as these? I made this photo of serial modules and my DPS5005 has exactly the same:

![ruideng-connector](https://user-images.githubusercontent.com/276504/119258849-bc7d1000-bbcb-11eb-9bd5-44eee1b62a60.png)

JST GH seems to look different...

**Comment by kanflo** [comment]
A bit late perhaps, but yes. I have the same cables.
