### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by mariusdp** [kanflo/opendps#251]
Hi All,

1st sorry if this is in the wrong place. Now the Q: Does anyone have the factory FW for a DPS5015? Please... If any better place to get that please direct me. Thank you.

**Comment by kanflo** [comment]
Do you mean the FW used in production to test the units after SMT/assembly?

**Comment by mariusdp** [comment]
> Do you mean the FW used in production to test the units after SMT/assembly?

I mean the FW the unit comes with when u buy new...

**Comment by mariusdp** [comment]
but i would get both if you have them. Thanks

**Comment by kanflo** [comment]
Neither of them are available online unfortunately.
