### ISSUE TITLE
Support for Miniware MDP-XP

### ISSUE THREAD

**Issue by violavon** [kanflo/opendps#252]
Support for Miniware MDP-XP devices (Miniware MDP-P905, MDP-P906 and MDP-M01)? I think there would be a lot of demand for it.

https://www.miniware.com.cn/product/mdp-xp-digital-power-supply-set/
https://www.miniware.com.cn/product/mdp-p906-mini-digital-power-supply/

https://notenoughtech.com/review/tools/miniware-mdp-xp/

**Comment by violavon** [comment]
https://github.com/Ralim/IronOS/discussions/1576

**Comment by kanflo** [comment]
While it seems like a very cool product, I will not find the time for such a large undertaking. I may need to get one though, thanks for telling about it.
