### ISSUE TITLE
Output Voltage is not set if only remote control is used

### ISSUE THREAD

**Issue by pgunzelmann** [kanflo/opendps#32]
powering up the DPS5005 and try controll by dpsctl.py only, the output voltage seems not to be set. 

>python dpsctl.py -d com4 -v -u 1000
Communicating with com4
TX  7 bytes [7e 02 03 e8 47 15 7f]
RX 6 bytes [7e 82 01 6d db 7f]

>python dpsctl.py -d com4 -v -i 1000
Communicating with com4
TX  7 bytes [7e 03 03 e8 70 25 7f]
RX 6 bytes [7e 83 01 5e ea 7f]

>python dpsctl.py -d com4 -v -p 1
Communicating with com4
TX  6 bytes [7e 05 01 ef d4 7f]
RX 6 bytes [7e 85 01 f4 4c 7f]

>python dpsctl.py -d com4 -v -s
Communicating with com4
TX  5 bytes [7e 04 40 84 7f]
RX 17 bytes [7e 84 01 13 df 03 e8 00 00 00 00 03 e8 01 59 7b 7f]

V_in  : 5.08 V
V_set : 1.00 V
V_out : 0.00 V (on)
I_lim : 1.000 A
I_out : 0.000 A

also the new set values are not shown in the dps5005 display (may its a following issue)

**Comment by kanflo** [comment]
That's too bad. I might have messed things up with the lashes CC work, could you try an earlier commit, eg. ``43f0eba``?

**Comment by pgunzelmann** [comment]
Thanks for the hint. I can try. But bye the way I littele bit wondering why you have two different versions... For my understanding the setting values shuould be max current and max volltage.. And the connected resistance decide  which type of controll will applay.. 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 13.05.2018, 07:50, Johan Kanflo <notifications@github.com> schrieb:
That's too bad. I might have messed things up with the lashes CC work, could you try an earlier commit, eg. 43f0eba?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kanflo/opendps","title":"kanflo/opendps","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kanflo/opendps"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kanflo in #32: That's too bad. I might have messed things up with the lashes CC work, could you try an earlier commit, eg. ``43f0eba``?"}],"action":{"name":"View Issue","url":"https://github.com/kanflo/opendps/issues/32#issuecomment-388603388"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [kanflo/opendps] Output Voltage is not set if only remote control is used (#32)","sections":[{"text":"","activityTitle":"**Johan Kanflo**","activityImage":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","activitySubtitle":"@kanflo","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"kanflo/opendps\",\"issueId\":32,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"kanflo/opendps\",\"issueId\":32}"},{"targets":[{"os":"default","uri":"https://github.com/kanflo/opendps/issues/32#issuecomment-388603388"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":333875436}"}],"themeColor":"26292E"}

**Comment by pgunzelmann** [comment]
Whit an earlier commit (43f0eba) i done the same procedure. Now the status querry show the expected results.

V_in  : 5.07 V
V_set : 1.00 V
V_out : 0.97 V (on)
I_lim : 1.000 A
I_out : 0.000 A

Thanks for quick response and good luck to clean up the "messed things" ;)

**Comment by kanflo** [comment]
Glad it's working, sorry I broke things and above all thanks for reporting it. I will keep this issue open until Imend things.

**Comment by kanflo** [comment]
Remote control is fixed now, please let me know if I was wrong.
