### ISSUE TITLE
bin file for testing

### ISSUE THREAD

**Issue by dziedzic99** [kanflo/opendps#33]
Hi, i think I fail to compile opendps correctly.
To test that hypothesis - can someone please post a working opendps.bin file?

**Comment by dziedzic99** [comment]
I manage to flash it according to command output, bootloader works, but the program itself doesn't. The screen doesn't light up and I can't talk to it over UART.

**Comment by kanflo** [comment]
That's odd. Did you flash the boot loader and app in the correct order (boot loader, then app)? I noticed that OpenOCD overwrites the beginning of the app when flashing the boot loader.

**Comment by kanflo** [comment]
Ping @dziedzic99. Did you have any success in flashing your unit?

**Comment by dziedzic99** [comment]
Yup. I flashed it finally but only after I wiped my toolchain clean and
reinstalled it.
