### ISSUE TITLE
New board version? w/ Bluetooth and USB Board

### ISSUE THREAD

**Issue by ElectricCookie** [kanflo/opendps#35]
Hey there,
I just received my DPS Power-Supply. It's a DPS5005 to be exact. I also ordered the additional Parts (Bluetooth and USB Board) along with it. Now my Board has a connector for these to interface, but I'm unsure whether these pins are the ones referenced for the installation of OpenDPS. 

Attached are some images of the DPS I received.

<img src="https://user-images.githubusercontent.com/18628516/40914787-d3c0ce9c-67f9-11e8-8b61-ef7547d0b6b8.jpg" width="250" />
<img src="https://user-images.githubusercontent.com/18628516/40914788-d3dd9ab8-67f9-11e8-8908-3f721a0af5e2.jpg" width="250" />
<img src="https://user-images.githubusercontent.com/18628516/40914789-d3fce792-67f9-11e8-95db-9fc8d83d25d7.jpg" width="250" />
<img src="https://user-images.githubusercontent.com/18628516/40914790-d41fe62a-67f9-11e8-9452-7897803cb65e.jpg" width="250" />
<img src="https://user-images.githubusercontent.com/18628516/40914791-d43b64f4-67f9-11e8-9326-7adad7a7efdc.jpg" width="250" />

Off topic: I'm also thinking about an OpenDps companion App for PC or Mobile... Maybe if I find some time.

**Comment by kanflo** [comment]
You need to carefully dislodge the device from the housing, then you will hopefully see the SWD port on the front to the top right.

**Comment by ElectricCookie** [comment]
Thanks!

**Comment by kanflo** [comment]
Feel free to reopen this issue if your PCB looks different. A companion app would be way cool!
