### ISSUE TITLE
Overvoltage limit protection in CC mode

### ISSUE THREAD

**Issue by Robin10155** [kanflo/opendps#41]
Can we add an overvoltage limit in constant current mode?

**Comment by kanflo** [comment]
That would be doable. I just need to figure out how it would work out UI wise.

**Comment by Robin10155** [comment]
Constant voltage mode is doing something similar already. We set constant voltage value using voltage setting and current limit using current setting. Similarly in constant current we can set constant current value using current setting and voltage limit using voltage setting.

**Comment by jimmyw** [comment]
@Robin10155 Did a small redesign, and added this feature, se my branch: https://github.com/jimmyw/opendps

**Comment by piit79** [comment]
@jimmyw Could you please post a picture of your modified UI? :-)

**Comment by Xenoamor** [comment]
I'll have a look at implementing this soon.
I think adding a `handle_ovp()` function into the `adc1_2_isr` would be the best way to do this. This limit can then be set with `pwrctl_set_vlimit()`
