### ISSUE TITLE
On/Off toggle on short circuit

### ISSUE THREAD

**Issue by f0086** [kanflo/opendps#51]
When I connect plus and minus, the background flashes white and it turned of. If I then got another short circuit (connecting plus and minus again), the device turned ON, and stays ON!

Maybe this is related to #42 and #36 ?

**Comment by kanflo** [comment]
That would _really_ no be the intended behaviour. I will have a look at it, thanks.

**Comment by kanflo** [comment]
Yes, #42 fixed it. I actually fried a '5005 in the process, should probably sign up at patreon.com...

**Comment by Cabalist** [comment]
Please do!  You'd have my subscription.  :)

**Comment by kanflo** [comment]
Thanks! I tried but the sign-up part of Patreon is down for maintenance :D

**Comment by kanflo** [comment]
Gah. Encountered the issue when testing #49 that obviously does not carry the #42 fix. Probably time to call it a day, good night all.

**Comment by Xenoamor** [comment]
+1 for patreon
