### ISSUE TITLE
Limit voltage if > input voltage

### ISSUE THREAD

**Issue by f0086** [kanflo/opendps#52]
I use an old Thinkpad power supply for the input source for my DPS5005, which gives me 20.5V. Would it be nice if the output voltage will be caped to that voltage, because higher voltages makes no sense (no boost converter). Or do I miss something here?

**Comment by kanflo** [comment]
That feature apparently got lost in the UI overhaul. Thanks for reporting.

**Comment by Xenoamor** [comment]
I'm still seeing this issue on my branch...
