### ISSUE TITLE
Unable to set voltage when V_In > 32.7V

### ISSUE THREAD

**Issue by Jantek** [kanflo/opendps#55]
When I am in the CV-mode and V_In is greater than 32.7V I can't setup the voltage correctly. As you can see here in the pictures the voltage jumps between 0V and approximately 83V. Even if I am at the last digit.

My suggestion is a overflow of a 16-bit signed variable as the problem seems to happen when V_In is greater than 2^15 mV.

![img_20181026_164009](https://user-images.githubusercontent.com/2740778/47575754-10a3b300-d943-11e8-856e-44b6eeb5aec2.jpg)
![img_20181026_164014](https://user-images.githubusercontent.com/2740778/47575755-10a3b300-d943-11e8-9b53-26472c30b511.jpg)

DPS5015 and DPS5020 seem to act the same to me. I have compiled the source with ```make -C opendps MODEL=DPS5015 MAX_CURRENT=9999```

I also use a DP50V5A with the same issue.

_Originally posted by @Jantek in https://github.com/kanflo/opendps/issues/50#issuecomment-433442446_

**Comment by kanflo** [comment]
I have to admin I have never powered my DPS:es above 12V ;)
