### ISSUE TITLE
Can set output voltage higher than possible output

### ISSUE THREAD

**Issue by Xenoamor** [kanflo/opendps#70]
Is the change made to solve #52 correct? It seems like we want to limit the settable output to what the device can actually output so around 90-95% of the input voltage

**Comment by kanflo** [comment]
Ah, the max output voltage for CV should be set here: https://github.com/kanflo/opendps/blob/24ccfcc0b94cee5c165de112591e8eb8a6b5cbc1/opendps/func_cv.c#L288
