### ISSUE TITLE
number_draw() could be improved to handle any font

### ISSUE THREAD

**Issue by Xenoamor** [kanflo/opendps#80]
There are a lot of magic numbers in number_draw() that could be removed to allow for better rendering of all fonts. The widest glyph could be determined by the font generator in #79.

https://github.com/kanflo/opendps/blob/507da617981f2bfcc4cb33ded8c4db5a4e1a4a8a/opendps/uui_number.c#L111-L164

I'm happy to work on this once we have some of the outstanding font pull requests merged in

**Comment by kanflo** [comment]
Sounds great, I will have a look at the font PRs in the coming week.

**Comment by kanflo** [comment]
I noticed this one was actually fixed some time ago.
