### ISSUE TITLE
ili9163c_draw_pixel x and y are wrong

### ISSUE THREAD

**Issue by Xenoamor** [kanflo/opendps#96]
For some reason to get a white dot in each corner pixel of the screen I have to use:
```
ili9163c_draw_pixel(3, 2, WHITE);     // Expected 0,0
ili9163c_draw_pixel(3, 129, WHITE);   // Expected 0,127
ili9163c_draw_pixel(130, 2, WHITE);   // Expected 127,0
ili9163c_draw_pixel(130, 129, WHITE); // Expected 127,127
```

I had to remove the bounds checking in `ili9163c_draw_pixel` function:
```
void ili9163c_draw_pixel(int16_t x, int16_t y, uint16_t color)
{
    //if (ili9163c_boundary_check(x,y)) return;
    //if ((x < 0) || (y < 0)) return;
    ili9163c_set_window(x,y,x+1,y+1);
    write_data16(color);
}
```
To allow me to draw "out of bounds"

**Comment by Xenoamor** [comment]
Adding these offsets into `ili9163c_set_window` fix it
```
void ili9163c_set_window(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1)
{
    write_command(CMD_CLMADRS); // Column
    if (rotation == 0 || rotation > 1) {
        write_data16(x0 + 3);
        write_data16(x1 + 3);
    } else {
        write_data16(x0 + __OFFSET); //
        write_data16(x1 + __OFFSET); //
    }

    write_command(CMD_PGEADRS); // Page
    if (rotation == 0) {
        write_data16(y0 + __OFFSET);
        write_data16(y1 + __OFFSET);
    } else {
        write_data16(y0 + 2); //
        write_data16(y1 + 2); //
    }
    write_command(CMD_RAMWR); // Into RAM
}
```

... weird. I'm not too comfortable just changing this for the sake of it. I'll experiment some more

**Comment by Xenoamor** [comment]
Nope.. that certainly seems to be the case. Can someone else test their device to check?

**Comment by tzarc** [comment]
Busy weekend; will confirm this evening.

**Comment by kanflo** [comment]
That's odd, I will give it a try tomorrow. Unrelated, I have been thinking of a screen shot function.

**Comment by Xenoamor** [comment]
That would be a really neat way of showing off custom graphics/fonts. (_and save me having to take pictures under magnifiers_)

**Comment by kanflo** [comment]
Hmm, definitely something going on here. I added this to `main_ui_tick()`

```
    uint32_t x_offset = 3;
    uint32_t y_offset = 2;

    for (uint32_t y = 0 + y_offset; y < 128 + y_offset; y++) {
        ili9163c_draw_pixel(x_offset, y, YELLOW);
        ili9163c_draw_pixel(127, y, YELLOW); // No adding x_offset here :-/
        ili9163c_draw_pixel(128, y, YELLOW); // Doesn't appear
    }

    for (uint32_t x = 0 + x_offset; x < 128 + x_offset; x++) {
        ili9163c_draw_pixel(x, y_offset, YELLOW);
        ili9163c_draw_pixel(x, 127, YELLOW); // No adding y_offset here :-/
        ili9163c_draw_pixel(x, 127 + y_offset, YELLOW); // Doesn't appear
    }
```
producing this:

![image](https://user-images.githubusercontent.com/931076/51210790-f3fc9300-1913-11e9-9f8c-06aac9a7a2a8.png)

(sorry for the dust ;)

Long pressing SET inverts the display and reveals things are off:

![image](https://user-images.githubusercontent.com/931076/51210847-168eac00-1914-11e9-88b2-2bb3d33b6b99.png)

Not only is the display buffer offset, we cannot address the last pixel columns/rows.

**Comment by Xenoamor** [comment]
> I had to remove the bounds checking in `ili9163c_draw_pixel` function:
> 
> ```
> void ili9163c_draw_pixel(int16_t x, int16_t y, uint16_t color)
> {
>     //if (ili9163c_boundary_check(x,y)) return;
>     //if ((x < 0) || (y < 0)) return;
>     ili9163c_set_window(x,y,x+1,y+1);
>     write_data16(color);
> }
> ```
> 
> To allow me to draw "out of bounds"

Did you apply this change?

**Comment by kanflo** [comment]
Bummer! Forgot about that one, will test again.

**Comment by kanflo** [comment]
Without the bounds checking, I get the expected bounding box at the edges of the screen with the code I posted above (the "Doesn't appear" lines). I guess the ILI9163 driver needs fixing.

**Comment by kanflo** [comment]
Defining this one instead:

https://github.com/kanflo/opendps/blob/cf5e5943db4ac5ff9f7e531cd1b4e430b1d3e0a4/opendps/ili9163c_settings.h#L7

and adding x offset 3 and y offset 2 to 

https://github.com/kanflo/opendps/blob/cf5e5943db4ac5ff9f7e531cd1b4e430b1d3e0a4/opendps/ili9163c.c#L258

does the trick. Normally I would prefer to study the data sheet for the display though...
